### ISSUE TITLE
Hdfs service should be mandatory for HBase and Hive

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/registry#127]
If user creates an environment by picking HBase/Hive from an HDP cluster added via ambari then HDFS from same cluster should automatically added by UI to the environment. Reason is HBase has hbase.rootdir that uses hdfs-site.xml core-site.xml to connect to HDFS. Without HDFS being present in environment storm topology fails at runtime throwing an exception from HBaseClient that it cannot connect to hdfs.

**Comment by priyank5485** [comment]
@shahsank3t  Can you or someone familiar with UI look in to this?
@HeartSaVioR I see that we are packaing hdfs-site.xml and core-site.xml with the topology jar if we have just HBase sink in the topology. Just curious about the logic used to pick hdfs-site and core-site if we have two hdfs services(both from different service pools) added to the same environment? Will it pick the right one?

**Comment by HeartSaVioR** [comment]
@priyank5485 
No we can't determine which is the right one, so the services which rely on configuration file like HDFS, HBase, and Hive should be selected only once.

Maybe better to prevent selecting same service multiple time in an environment until we support multi-clusters for all services properly. That may be an unnecesary limitation for other services, but safest way to avoid that issue.

We might also want to force selecting cluster for each component in order to provide corresponding configurations while deploying. 
(Maybe also better to change some fields which are dependent on cluster to be read-only.)

cc. @harshach @shahsank3t

**Comment by HeartSaVioR** [comment]
Btw I guess this issue is filed to wrong project. :) Did you intend to file this issue to the Streamline project?

**Comment by priyank5485** [comment]
@HeartSaVioR you are right. will refile in streamline
