### ISSUE TITLE
Sanitize mysql create_tables scripts

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/registry#189]
In many columns we have defined column types as `varchar(256)`. This can potentially throw error during table creation when using utf-8 charset. Revisit the column definitions and use sane limits with max = 255 instead of 256.

Exception in thread "main" java.sql.SQLSyntaxErrorException: (conn:12499) Specified key was too long; max key length is 767 bytes

**Comment by satishd** [comment]
Right, it should be done for below reasons
- utf-8 requires 3 bytes for each characters, 3*256 = 768 and column key limit on innodb is 767
- utf8mb4 requires 4 bytes, so max length can be 191 instead of 255
- 256 requires 2 bytes which is unnecessary.

I am not sure why these were created with 256 though. We can have this as 255 and when user uses utf8mb4 then they can change their scripts to have respective length restriction as 191.

**Comment by satishd** [comment]
#190
