### ISSUE TITLE
Invalid schema still stored

### ISSUE THREAD

**Issue by unaipme** [hortonworks/registry#312]
Hi!

When I tried to add a new schema to the registry, I had a typo and I got an "Given schema is invalid" error. I corrected the typo in my schema and clicked "Save", and this time a new error showed up: "[Storing the given SchemaMetadata [SchemaMetadata{...}] is failed]". This is caused because even though the first error is prompted, the schema is still saved.

In addition, taking into account that there is no "direct" way to delete an existing schema, I have to deal with a schema version that will never work nor be used.

Bye!

**Comment by unaipme** [comment]
@raju-saravanan It's 0.3.0

**Comment by satishd** [comment]
@unaipme There are two steps involved when you add new schema version with metadata config like name, description, compatibility etc
- create schema metadata like name, description, compatibility etc.
- add new schema version for the above schema metadata

It may be possible that first step is successful and second step is failed because of wrong schema text. But when you correct that text and try to create again, UI may be trying to create metadata which already exists and it may be adding new schema version.

@shahsank3t Can you look into this?

**Comment by unaipme** [comment]
Hi, @satishd . It's actually only one step, at least for me it shows up like in the screnshot below:

![screenshot](https://user-images.githubusercontent.com/9933703/33599692-2fe71b0e-d9a7-11e7-9744-c32a765786f9.PNG)

**Comment by satishd** [comment]
@unaipme UI shows as one step but there are two steps to the backend.

**Comment by shahsank3t** [comment]
I'll take a look at this today.

**Comment by shahsank3t** [comment]
> It may be possible that first step is successful and second step is failed because of wrong schema text. But when you correct that text and try to create again, UI may be trying to create metadata which already exists and it may be adding new schema version.

@satishd Yes, that's exactly what's happening. I am adding a fix where if the schema has been created but adding version(second step) fails, only that will be called again by clicking save.

@unaipme Thanks for reporting the bug, I'll fix and raise a PR soon.

**Comment by shahsank3t** [comment]
Raised PR: https://github.com/hortonworks/registry/pull/318
