### ISSUE TITLE
Use hazelcast for HA cache management

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/registry#406]

**Comment by michaelandrepearce** [comment]
Why not Apache ignite? Especially if looking to one day incubate this in Apache

**Comment by HeartSaVioR** [comment]
Hazelcast is also Apache 2 license so there's no problem even in point of ASF project's view.
https://github.com/hazelcast/hazelcast

While I would like to see comparison and discussion based on comparison instead, for me it doesn't make sense that we need to consider ASF project first because we are planning to donate the project to ASF.

**Comment by hmcl** [comment]
I worked initially on a patch that would allow for pluggable cache support, e.g Redis, Hazelcast. I have on my local branch an improvement of the initial code almost concluded. If possible it would be ideal to incorporate this change with that patch. @raju-saravanan what is the time frame for this change. Have you started working on it yet ?

**Comment by michaelandrepearce** [comment]
No entirely not a license issue. But I don’t see why this has to be hazelcast? 

Surely if going Apache the idea is to embrace and cross pollinate.

If you could say I need feature x that isn’t present in Ignite I’d understand that. 

If anything using ignite I can see further advantages for scheme registry such as could use its sql layer to then use its clustered native persistence to provide out the box replicated and local persistent storage for registry without need for external db.

**Comment by michaelandrepearce** [comment]
@hmcl is this custom or based on java spec JCache api? If able to implement using JCache this makes it very pluggable with all major cache vendors, terracotta, ignite, Hazelcast, coherence

**Comment by HeartSaVioR** [comment]
That's what I'm just saying: why we don't say about any comparison but just saying we should use something? Please note that I commented based on the title and your earlier comment which doesn't contain any of details.

Even both support features we need, there're lots of point of view outside of features: how many developers are familiar with such libs/frameworks (lower the wall to possible contributors), how far the lib/framework is stabilized, how much the maintenance cost is (because as I wear HWX hat on, it would be a new dependency which we should support. Even if I don't wear, it should be considered seriously for end-users.).

Are we really wanting to pick something which helps us to lower the wall to ASF incubator? I'm sorry but I think ASF shouldn't do that if it is in place. (DISCLAIMER: I'm a PMC member of Apache Storm.)

@raju-saravanan , why not elaborating which features are needed actually? If we use Hibernate or so we may not even need to enumerate, but we have our own storage implementation so we need to enumerate and ideally have comparison between candidates.

**Comment by michaelandrepearce** [comment]
@HeartSaVioR I think would be best as noted if Jcache api meets the needs here if so it makes the code very agnostic as is a Java spec like JMS is, and most main vendors/products all implement

**Comment by michaelandrepearce** [comment]
https://www.jcp.org/en/jsr/detail?id=107

**Comment by michaelandrepearce** [comment]
https://docs.oracle.com/middleware/1213/coherence/tutorial/jcache.htm

https://hazelcast.com/use-cases/caching/jcache-provider/

https://ignite.apache.org/use-cases/caching/jcache-provider.html

**Comment by HeartSaVioR** [comment]
@michaelandrepearce 
I definitely love the idea to check Jcache API. Even if we found we can't rely on that, I'd still love to have pluggable interface and have (several) implementations so that choosing the cache is left to end-users.

**Comment by hmcl** [comment]
@michaelandrepearce answering your [comment](https://github.com/hortonworks/registry/issues/406#issuecomment-365427603). The initial implementation I worked on was for this [Cache](https://github.com/hortonworks/registry/blob/master/cache/src/main/java/com/hortonworks/registries/cache/Cache.java) interface, which thinner interface than the JCache Cache interface.

There are differences of opinions about JCache. Not all cache providers provide an implementation. The main JCache Cache interface exposes a lot methods such as invoke, iterator, which from what I heard are hard to support in some cache implementations.
