### ISSUE TITLE
UI load wrong schema when paginating through results 

### ISSUE THREAD

**Issue by gmcoringa** [hortonworks/registry#550]
When you paginate through the schemas, loading schemas from pages all pages except page one brings the wrong schema.

Reproduce the error following the steps:
* Open any schema from the first page
* Advance to any page
* Open any schema from the new page

Reproduced in versions `0.5.3` and `0.7.0`

**Comment by joylyn** [comment]
@gmcoringa I have checked on version `0.7.0` and it looks fine. Whereas for `v0.5.3`, the issue is reproduced , but this fix was included in versions `0.5.1`  and `0.7.0`.
Can you provide some more details or screenshots of the issue you are facing in version `0.7.0` ?
cc @satishd We may have to bring this fix (https://github.com/hortonworks/registry/commit/026cefde42b89eb1197073b522eb6e6064937cbb) to v`0.5.3`  if it is the cause.

**Comment by gmcoringa** [comment]
@joylyn I've try to reproduce with a fresh install and this error didn't happen.
In my integration environment we have 28 schemas, each with multiple versions, including archieved.

Is there any specific information that might help you?

**Comment by mcdougallster** [comment]
https://community.cloudera.com/t5/Support-Questions/Schema-Registry-UI-displays-wrong-schema-contents-after/m-p/209149 -- seems similar

**Comment by gcsaba2** [comment]
Fixed
