### ISSUE TITLE
Updating schema description in the UI does not work

### ISSUE THREAD

**Issue by nextropia** [hortonworks/registry#66]
To replicate:
* edit an existing schema; the Add Version dialog is displayed
* change the description and click OK; "Version added successfully" is displayed

Expected result:
* schema now has new description

Actual result:
* description has not changed, even after refreshing the page

**Comment by shahsank3t** [comment]
@nextropia - I assume you didn't change anything in your schema and just updated the description, which didn't even add another version nor update the description (although we show Version added message).
If my assumption is right, we should surely show some different message, since we are not adding another version here. If you edit your schema and try again, you will see a new version with its particular (new) description.

@satishd - Even if we add a new schema which has same fields which are already present in one of the older versions, should we be updating the description for that particular version?

**Comment by satishd** [comment]
@shahsank3t Yes, we do not allow updating versions for now. You can check if the returned version is same as the current version then you can show relevant message to the user.

**Comment by shahsank3t** [comment]
@satishd Will do that relevant changes but I am also wondering if the user should be able to update only the description of that particular version or not.

**Comment by nextropia** [comment]
I would argue the description should be updated.

What happens if I submit a schema with no field changes BUT with a
description change via the API? Will the description get updated?

If yes, then the UI should have the same behavior.

If no, it seems silly not to allow updates to the description without any
field changes.

**Comment by shahsank3t** [comment]
PR available for this issue: https://github.com/hortonworks/registry/pull/69
