### ISSUE TITLE
Schema Registry needs to allow users to paste a schema

### ISSUE THREAD

**Issue by markap14** [hortonworks/registry#72]
Previous versions of Schema Registry allowed me to paste a schema in, which was very nice. Now it requires that a file be uploaded. This means that I have to copy the schema, paste into vi, save, go back to web app, upload, navigate to file... While I can appreciate the desire to upload a file if you already have a file saved off, it is much more of a pain if you don't have the schema already saved in a file. I would like to have the option to either paste the text into the UI or uploading an existing file.

**Comment by satishd** [comment]
+1 to have both file dialog and text box to enter schema text.

**Comment by shahsank3t** [comment]
Thanks for the suggestion @markap14 
Raised https://github.com/hortonworks/registry/pull/79 to address this suggestion.

**Comment by satishd** [comment]
<img width="561" alt="screen shot 2017-05-03 at 9 39 42 am" src="https://cloud.githubusercontent.com/assets/2577761/25647996/c810bfe2-2fe4-11e7-88c2-ef16e2b4dac0.png">
@shahsank3t Is this a standard way of describing about a field?
All uppercase looks weird to me, you may want to have text like (Type or Drop a file) instead of all uppercase.

**Comment by shahsank3t** [comment]
@satishd Missed out changing the case there. I have updated the PR with the changes. Thanks.

**Comment by satishd** [comment]
Verified and merged into master. Thanks @shahsank3t
