### ISSUE TITLE
Add support for Kafka Header Registry

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#87]
As you'll see KIP-82 got adopted and submitted.

This means as of Kafka 0.11, Kafka will have headers. 

Kafka Record, the value is simply a byte[] as such delegates the handling of what schema or how to decode that to the consumer, which obviously solutions like schema registry provide. 

The Kafka Header record, introduces a String key and a value byte[], following this, as such having support for being able to register the kafka header value types.

It would be great to support schema registry for headers where the schema can be a primitive, int8, int16, int32, int64, float32, float64, boolean, bytes, string or more complex avro like schemas. 

The idea would be a subject for lookup could be the topic + header key, or if all values for the same key within an organisation then simply the subject could just be header key.

Is this possible to record with the current schema repo api's? as in is the mapping agnostic and just simply subject = topic + ".key" or subject = topic + ".value" as such we could make subject = topic ".header." + headerKey

**Comment by satishd** [comment]
Current default convention for schema names is <topic-name>:v and <topic-name>:k for values and keys respectively.

There is a discussion going on [here](https://groups.google.com/d/msg/registry/2HcXO3j6Iws/WdkEfLK-AAAJ) to change this convention for values as it is causing confusion to users.

Current api in `KafkaAvroSerializer` mentioned here takes care of handling computing schema names is mentioned [here](https://github.com/hortonworks/registry/blob/master/schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/kafka/KafkaAvroSerializer.java#L62). Same API can be enhanced to handle computing headers schema when we support a kafka release which supports headers. 

We may want to utilize kafka's message headers support to pass protocol information as part of header instead of prepending with the value payload. Initial thoughts on ser/des may be along the lines of [MessageContextBasedAvroDeserializer](https://github.com/hortonworks/registry/blob/master/schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotSerializer.java#L52) and [MessageContextBasedAvroSerializer](https://github.com/hortonworks/registry/blob/master/schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializer.java#L61).

**Comment by nextropia** [comment]
> We may want to utilize kafka's message headers support to pass protocol information as part of header instead of prepending with the value payload.

I think this is badly needed. It would be great if the payload is pure Avro so it can be decoded independently of the Hortonworks serde.

**Comment by satishd** [comment]
@nextropia You can submit an issue and we can implement it once kafka is released with headers support.

**Comment by harshach** [comment]
@nextropia can you file a issue for this.

**Comment by nextropia** [comment]
Already did! #108

**Comment by kamalcph** [comment]
#488
